#!/usr/bin/env bash

s=$1

case "$s" in
    dave)
        echo hi dave
        ;;
    buddy)
        echo ohh there he is
        ;;
    guy)
        echo uh oh here comes
        ;;
    *)
        echo I don't know who you are
        ;;
esac
