#!/usr/bin/env bash

declare -a first_array
first_array=(
    foo 
    bar 
    baz
    "hello ther"
)
second_array=("${first_array[@]}")
second_array+=(buddy guy joe)

for item in "${second_array[@]}"; do
    echo "item: $item"
done
