#!/usr/bin/env bash

mapfile -t array < data.txt

printf '<%s>\n' "${array[@]}"

mapfile -t -n 2 foo < data.txt

printf '<%s>\n' "${foo[@]}"

my_func(){
    local line=$1
    echo "(mapfile) called with line: $line"
}
# the readarray is the alias of mapfile
mapfile -t -C my_func -c 1 bar < data.txt
printf '<%s>\n' "${bar[@]}"
