#!/usr/bin/env bash

# words=$(grep d /usr/share/dict/cracklib-small)
#
# i=0
# while read -r word; do
# # for word in "$words"; do
#     echo "$word"
#     ((i++))
# done <<< "$words"

i=0
while read -r word; do
    echo "$word"
    ((i++))
done < <(grep d /usr/share/dict/cracklib-small)

echo "We have found $i words"
