#!/usr/bin/env bash

hello(){
    local s=$1
    echo "hello $s"
}

goodbye(){
    local s=$1
    echo "goodbye $s"
}

if (( $# == 0 )); then
    echo "name required!" >&2
    # when there is no user input, the script will stop at the next line
    exit 1
fi

for name in "$@"; do
    if [[ $name == d* ]]; then
        hello "$name"
    elif [[ $name == b* ]]; then
        hello "$name"
    else
        goodbye "$name"
    fi
done

if [[ $? == 1 ]]; then
    echo $?
    echo "The program exited with code 1."
fi
