#!/usr/bin/env bash

array=()

while read -r line; do
    array+=("$line")
done < /usr/share/dict/words

max="${#array[@]}"
echo $max

for ((i=0; i<$max; i++)) ; do
    echo "${array[i]}" > pipe2
done
